Fix running on Spark broken by date_spine
For some reason, dbt is confused by the same-named macros:

21:36:32  Encountered an error:
Compilation Error in model metric (models/post_processing/metric.sql)
  macro 'dbt_macro__default__date_spine' takes not more than 0 argument(s)

  > in macro date_spine (macros/sql/date_spine.sql)
  > called by macro default__date_spine (macros/fhir_analysis_macros/date_spine.sql)
  > called by macro date_spine (macros/fhir_analysis_macros/date_spine.sql)
  > called by macro default__date_spine (macros/fhir_analysis_macros/date_spine.sql)
  > called by model metric (models/post_processing/metric.sql)

Also remove unnecessary parenthesis.

PiperOrigin-RevId: 517124804
Change-Id: I76c7d7cd166aceb84b6285464f2eecfb836b1274